### ISSUE TITLE
Updated Use Case and DFD (v4)

### ISSUE THREAD

**Issue by brentmac94** [brentmac94/ISQA-3420-A1#13]
The Use Case has been updated per your suggestion. Please review changes.
Once the DFD looks good, I will add the third use case.

Thank you!

**Comment by germonprez** [comment]
A few comments: 

1) Package License and Info Request --should be--> Software Project License and Vulnerability Request

You will have to make this, and related changes, through the DFD. 

2) Why are the dataflows that the Manager and Developer request named different things? These can have the same names. 

3) Updated Policy Documents should be more a request for the documents so that they can be edited. In that area as well, currently policy documents should be more along the line of the one policy document that was requested. 

I hope this helps. 

MG

**Comment by brentmac94** [comment]
My main changes are below. Please let me know what other suggestions you have. Thank you!
- Updated DFD (v5) 
- Updated Data dictionary based on new datastores and processes. 
- Added a third use case

**Comment by germonprez** [comment]
Thanks for the updates. The structure is nicely done. Largely editorial issues: 

1) OSS Results going to the developer --should be--> Package, License, & Vulnerability Info Response 

2) The Manager will also request vulnerability information (not just package and license)

3) The updating of policies (and adding new policy) is not 100% clear. 

Again, great structure, just some grammar issues. 

MG
